Bugfix/mms 816
Open-MBEE/mms-alfresco pull request #122
Opened 2017-08-10 00:11 UTC by lauraerinmann

2017-08-10 03:35 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +    protected JSONObject handleArtifactMountSearch(JSONObject mountsJson, String filename, WebScriptRequest req) {
getting the commit (if given) and timestamp (or null) should be done before calling this function since this function is recursive - timestamp instead of req should be passed instead. once a recursion is called the commit is not relevant since the project and ref has changed

2017-08-10 03:39 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +            getVersionedArtifactFromParent(siteNode, projectId, parentRef.first , filename, parentRef.second,
timestamp passed should be the earlier of parentRef.second or original timestamp

2017-08-10 03:41 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +                Version nearest = emsNodeUtil.imageVersionBeforeTimestamp(versions, timestamp);
there may not be an image version earlier than timestamp in this ref

2017-08-10 03:45 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
> +                execQuery(String.format("SELECT parent FROM refs WHERE deleted = false AND refId = '%s'", refId));
timestamp needs to be gotten from parentCommit, may need to do a join with commits table

2017-08-14 17:01 UTC, HuiJun requested changes

2017-08-14 17:01 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/WorkspacesPost.java
> +        EmsNodeUtil emsNodeUtil = new EmsNodeUtil(projectId, sourceWorkId == null ? "master" : sourceWorkId);
Why are you using a String "master" and not the constant?

2017-08-15 00:36 UTC, merged