Feature/mms 830
Open-MBEE/mms-alfresco pull request #148
Opened 2017-08-29 21:02 UTC by EDKarlsson

2017-08-29 22:15 UTC, dlamoris commented
skimmed through it for now, are you taking into account the ref the commit is on? it seemed like you're just getting the first element with modified time <= the commit time? it can return the wrong one in the following case:
ref A 
   commit time 3 commitId given
   commit time 1 - element wanted
ref B
   commit time 2 - element updated
if asking for refs/A/element?commitId=3, it looks like it'll give back element at commit 2 instead of commit 1?

2017-08-29 22:23 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +    public JSONObject getElementsAtCommit(ArrayList<String> sysmlIdList, String commitId) {
this is always just returning one element? the signature seems like you can give it a list of multiple sysmlids and it'll return each of them at the commit

2017-08-29 22:38 UTC, dlamoris commented
also elastic only returns a limited amount of results as we set it, if you're asking for 500000 elements for example you may need to do it in chunks

2017-08-29 22:45 UTC, dlamoris commented
you should be able to have an array for must and filter also, it doesn't have to be one object

2017-08-31 17:20 UTC, dlamoris commented
also this won't know whether an element is deleted at the specified time since deletions are only tracked in commit objects

2017-08-31 19:50 UTC, HuiJun requested changes

2017-08-31 19:50 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
> +                    + "WHERE initialcommit IS NOT NULL ORDER BY commits.timestamp;");
If we're not using user supplied parameters, there's no need to do a prepared statement. Also, this looks terrible.

2017-08-31 19:50 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                        e.printStackTrace();
Wrong

2017-08-31 19:50 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            String timestamp = TimeUtils.toTimestamp(date.getTime());
As nice as it is, let's try to not reuse TimeUtils.

2017-08-31 20:14 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
> +                    + "WHERE initialcommit IS NOT NULL ORDER BY commits.timestamp;");
Alright I can fix that. What would you like the format to be?

2017-08-31 20:15 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                        e.printStackTrace();
Why is this wrong?

2017-08-31 21:16 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                        e.printStackTrace();
Don't use printStackTrace, use the logger. See any other class for examples.

2017-08-31 21:16 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                        e.printStackTrace();
oh, I didn't even noticed that. Fixed.

2017-08-31 21:17 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
> +                    + "WHERE initialcommit IS NOT NULL ORDER BY commits.timestamp;");
You can keep it in the prepared statement if you want, but I think it would be cleaner and easier to use String.format instead and just feed that into execQuery.

2017-08-31 21:23 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
> +                    + "WHERE initialcommit IS NOT NULL ORDER BY commits.timestamp;");
Alright I can do that

2017-08-31 21:41 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        JSONObject bool = new JSONObject().put("must", new JSONObject().put("term", new JSONObject().put("id", sysmlId)));
it's kinda hard to tell from here, but seems like the must level isn't needed, can't you just add the term query to the filter array?

2017-08-31 21:47 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        Search search = new Search.Builder(searchJson.toString()).addIndex(elementIndex).build();
since this is just getting one element now you can add the result limit to 1 and just return element instead of array, the first result should always be the right element now

2017-08-31 21:47 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        Search search = new Search.Builder(searchJson.toString()).addIndex(elementIndex).build();
Okay

2017-08-31 22:10 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        JSONObject bool = new JSONObject().put("must", new JSONObject().put("term", new JSONObject().put("id", sysmlId)));
I tried adding the term query to the filter using kibana and it didn't seem to like it.

The current query looks like this
```json
{
  "query": {
    "bool": {
      "must": {
        "term": {
          "id": "300"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "terms": {
                "_commitId": [
                  "d910c940-dd2f-4430-b6f7-eca6a0c07bf3",
                  "28666d24-f893-4a00-8110-282c330a32a7",
                  "98526772-339a-45d4-900b-a0156e0a0888",
                  "268a1f09-ea32-4986-9d7b-464bf1bec4d6",
                  "8d7b4d2c-d928-4f3c-947a-7dc65163571c"
                ]
              }
            },
            {
              "range": {
                "_modified": {
                  "lte": "2017-08-30T09:25:41.076-0700"
                }
              }
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "_modified": {
        "order": "desc",
        "mode": "max"
      }
    }
  ],
  "size": "1"
}
```

2017-08-31 22:30 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +import java.util.*;
I hate how IDEs do this. I guess it doesn't really matter, but I like to explicitly declare imports. Change or not, but if you don't, I probably will later on.

2017-08-31 22:32 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +            e.printStackTrace();
Didn't I comment on this line before? Was that a different line?

2017-08-31 22:35 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +import java.util.*;
fixed

2017-08-31 22:35 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        JSONObject bool = new JSONObject().put("must", new JSONObject().put("term", new JSONObject().put("id", sysmlId)));
it won't work if you add it at the same level as the bool - try either adding it as another object in the must or you can just get rid of the second bool and must altogether - basically set the must array as the value of "filter"

2017-08-31 22:35 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +            e.printStackTrace();
Different line but I fixed it.

2017-08-31 22:41 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        JSONObject bool = new JSONObject().put("must", new JSONObject().put("term", new JSONObject().put("id", sysmlId)));
Like this? This query doesn't return anything
```javascript
{
  "query": {
    "bool": {
      "must": {
        "term": {
          "id": "300"
        }
      },
      "filter": [
        {
          "terms": {
            "_commitId": [
              "d910c940-dd2f-4430-b6f7-eca6a0c07bf3",
              "28666d24-f893-4a00-8110-282c330a32a7",
              "98526772-339a-45d4-900b-a0156e0a0888",
              "268a1f09-ea32-4986-9d7b-464bf1bec4d6",
              "8d7b4d2c-d928-4f3c-947a-7dc65163571c"
            ]
          }
        },
        {
          "range": {
            "_modified": {
              "lte": "2017-08-30T09:25:41.076-0700"
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "_modified": {
        "order": "desc",
        "mode": "max"
      }
    }
  ],
  "size": "1"
}
```

2017-08-31 22:57 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        JSONObject bool = new JSONObject().put("must", new JSONObject().put("term", new JSONObject().put("id", sysmlId)));
I mean like this:
it's weird it didn't return anything? I was trying on my local with it
```javascript
{
  "query": {
    "bool": {
      "filter": [
        {
        "term": {
          "id": "300"
        }
      },
        {
          "terms": {
            "_commitId": [
              "d910c940-dd2f-4430-b6f7-eca6a0c07bf3",
              "28666d24-f893-4a00-8110-282c330a32a7",
              "98526772-339a-45d4-900b-a0156e0a0888",
              "268a1f09-ea32-4986-9d7b-464bf1bec4d6",
              "8d7b4d2c-d928-4f3c-947a-7dc65163571c"
            ]
          }
        },
        {
          "range": {
            "_modified": {
              "lte": "2017-08-30T09:25:41.076-0700"
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "_modified": {
        "order": "desc"
      }
    }
  ],
  "size": "1"
}
```

2017-08-31 23:15 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +        JSONObject bool = new JSONObject().put("must", new JSONObject().put("term", new JSONObject().put("id", sysmlId)));
I got it working, the test I was using wasn't using the correct timestamp.

2017-09-05 18:08 UTC, HuiJun approved these changes

2017-09-05 18:08 UTC, merged