Feature/mms 830
Open-MBEE/mms-alfresco pull request #154
Opened 2017-09-14 17:43 UTC by EDKarlsson

Handles if the elements have been just deleted, and deleted then resurrected and trying to get the element inbetween the commits.

2017-09-18 17:57 UTC, dlamoris requested changes

2017-09-18 17:57 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                        Date elementTimestamp = new Date(pastElement.getString(Sjm.TIMESTAMP));
think this should be MODIFIED, should use date format to parse
actually since it's using elasticid to check you don't even have to compare timestamp, if it exists it should be deleted

2017-09-18 17:57 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                        pastElement = eh.getElementByCommitId((String) n.get(PostgresHelper.LASTCOMMIT),
should check if element is deleted here, also should fix getElementByCommitId so it won't throw array index out of bounds exception (check length of hits)

2017-09-18 17:57 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +    public JSONObject getElementsLessThanOrEqualTimestamp(String sysmlId, String timestamp, ArrayList<String> refsCommitIds) {
update the query so it doesn't have to calculate score, see
https://github.com/Open-MBEE/mms/pull/148/files

2017-09-18 17:57 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +        if (commitId.equals(latestCommitId) && !elementNode.isDeleted()) {
if it is deleted can just return

2017-09-18 17:57 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    Date deleteTimestamp = null;
same as above, since it's using elasticid as the key this should already mean it's deleted, no need to check timestamp

2017-09-18 20:42 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +    public JSONObject getElementsLessThanOrEqualTimestamp(String sysmlId, String timestamp, ArrayList<String> refsCommitIds) {
also, should check this
https://stackoverflow.com/questions/30900984/elastic-search-terms-filter-max-terms

2017-09-19 16:38 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    Date deleteTimestamp = null;
Don't we always have to check the timestamp since we're concerned about whether or not the element has been resurrected?

2017-09-19 16:40 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    Date deleteTimestamp = null;
if the element has been resurrected, last element would already have that element (if it's resurrected before the commit we're interested in), if it's resurrected after the commit we're interested in, then we don't care.

2017-09-19 16:40 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +        if (commitId.equals(latestCommitId) && !elementNode.isDeleted()) {
Should it return null or an empty JSON Object?

2017-09-19 16:56 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    Date deleteTimestamp = null;
in any case, if it got into this if block the deletedTimestamp would always be later than the pastElement's modified time since the elasticId is unique

2017-09-19 17:01 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +        if (commitId.equals(latestCommitId) && !elementNode.isDeleted()) {
by what the caller is doing, empty JSON Object

2017-09-19 19:02 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            if (!deletedElementIds.containsKey(Sjm.SYSMLID)) {
this is always true

2017-09-19 20:23 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                if (((Date) n.get(Sjm.TIMESTAMP.replace("_", ""))).getTime() <= ((Date) commit.get(Sjm.TIMESTAMP.replace("_", ""))).getTime()) {
check the keys, indexes and type in n

2017-09-19 20:30 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            Node node = pgh.getNodeFromSysmlId(sysmlId);
node isn't used

2017-09-19 20:38 UTC, EDKarlsson commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            Node node = pgh.getNodeFromSysmlId(sysmlId);
I was gonna logic but realized it unnecessary -- removed it.

2017-09-19 20:42 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
> +        if(elementNode.isDeleted()){
this check should be moved to after line 295

2017-09-19 22:04 UTC, HuiJun approved these changes

2017-09-19 22:04 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +    public JSONObject getElementsLessThanOrEqualTimestamp(String sysmlId, String timestamp, ArrayList<String> refsCommitIds) {
Look into making this a Bulk request

2017-09-19 22:05 UTC, merged