Bugfix/mms 861
Open-MBEE/mms-alfresco pull request #180
Opened 2017-10-18 18:13 UTC by lauraerinmann

Carefully check lines 486-497 of EmsNodeUtil.

2017-10-18 18:44 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                docElasticIds.add(node.getElasticId());
check node.isDeleted() first

2017-10-18 22:58 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/Node.java
> +    public List<String> getElasticIds(List<Node> nodes) {
What this?

2017-10-18 23:00 UTC, HuiJun approved these changes

2017-10-18 23:05 UTC, dlamoris requested changes

2017-10-18 23:05 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/Node.java
> +    public List<String> getElasticIds(List<Node> nodes) {
is this used anywhere? this function shoudlnt' really be part of the node class

2017-10-18 23:05 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +    public JSONArray getDocJson(String sysmlId, int depth) {
should add back extended, don't need depth just set it to some high number

2017-10-18 23:05 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
put back extended

2017-10-18 23:05 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            if (sysmlId == null) {
this whole if else block can be put inside a if (!extended) block because adding extended info would already include the sitecharid

2017-10-19 00:04 UTC, dlamoris approved these changes

2017-10-19 01:18 UTC, merged