Feature/mms 864
Open-MBEE/mms-alfresco pull request #262
Opened 2018-03-29 22:56 UTC by HuiJun

2018-04-14 06:39 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
> +                if (parentId != childId) {
since commitParent isn't used anyways...and it has wrong data due to race conditions, just not do this?

2018-04-14 23:25 UTC, dlamoris requested changes

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                List<Pair<String, String>> refs = pgh.getRefsElastic();
pgh.getRefsElastic only gives back not deleted refs, but we still need to process deleted refs because a ref could have been branched/tagged from a ref that has since been deleted, stuff in the deleted ref could have updates that carry over

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    artifact.put("initialcommit", parentArt.get(Sjm.ELASTICID).getAsString());
initialcommit is wrong here, but isn't significant (should be initialcommit from parent ref's artifacts table)

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                String artifactId = name.startsWith("img_") ? name : baseId + "_" + extension;
can replace name var usages with baseId

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                cal.setTimeZone(TimeZone.getTimeZone("GMT"));
should this be GMT or pacific time?

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    eh.getElementsLessThanOrEqualTimestamp(artifactId, timestamp, inRefs, projectId);
the inRefs argument is wrong, the function is expecting a list of commitIds of the refs it can be in, not refIds.
this just checks whether the jsonobject is already in elastic right? it can just search by artifactId and the exact modified time? I think that should be the same on each run since the version modified date shouldn't change

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    artifactJson.addProperty(Sjm.CREATED, df.format(created));
if artifact already exists in table, created can be different, same for creator

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    artifactJson.addProperty(Sjm.CHECKSUM, "");
needs location and an actual checksum

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                            added.add(artifactJson);
the commitObject is ...various levels of wrong lol
added should not add artifactJson but id and elastic id of artifact, and type, also updated and deleted should be empty arrays

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    elasticId = check.get(Sjm.SYSMLID).getAsString();
this is not getting elasticId
I don't think this else block needs to be run? if it got here that means the right jsonObject is already in elastic for this file version and the initial creation should have the right stuff already

for adding inRefId, can do it for the whole ref artifacts table after all files in ref have been processed

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    map.put("initialCommit", elasticId);
missing lastcommit

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    pgh.insertCommit(commitId, GraphInterface.DbCommitTypes.COMMIT, creator,
we can also drop off the commitParents and projectMounts table for each project as part of this migration

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                String baseId = name.substring(0, name.lastIndexOf('.'));
also should collect baseId that doesn't start with img_ for a project, then update in elastic all elements that have that id with _artifacts: [baseId_svg and baseId_png]

2018-04-14 23:25 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    artifactJson.add(Sjm.INREFIDS, inRefIds);
would rather add this at the very end after the entire ref is processed, since version updates would normally wipe this out

2018-04-14 23:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                            eh.indexElement(commitObject, projectId, ElasticHelper.COMMIT);
if this somehow fails the first time, but the artifact json went in, it won't get a second chance, and also since commitId is generated each time, can't really use it to check existence, the exact modified or created time should be enough to check for existence

2018-04-14 23:33 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                int commitFromDb = pgh.getCommitId(commitId);
on multiple runs this'll create multiple commit entries in the table, should use exact create time?

2018-04-14 23:38 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        logger.info("Running Migrate_3_3_0");
what about all the elastic updates? (_isSite to _isGroup, adding type to added/updated elements in commit objects, updating index mappings?)

2018-04-16 14:43 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                cal.setTimeZone(TimeZone.getTimeZone("GMT"));
GMT should be correct.

2018-04-16 14:48 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    pgh.insertCommit(commitId, GraphInterface.DbCommitTypes.COMMIT, creator,
done

2018-04-16 17:59 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                        .addProperty(Sjm.LOCATION, url.replace("/d/d/", "/service/api/node/content/"));
i remember for versioned files, there's version2store involved in the url

2018-04-16 18:03 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    elasticId = check.get(Sjm.ELASTICID).getAsString();
can remove entire else block

2018-04-16 18:07 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                artifactsToUpdate.add(elasticId);
shouldn't add this inside the version loop, should get from table after since only the last version should have it

2018-04-16 18:11 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
>                                  Version version = (Version) it.next();
check if this is in ascending or descending time order?

2018-04-16 18:12 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresHelper.java
>              if (parentId > 0) {
can remove if block

2018-04-16 18:22 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +    private static final String searchQuery =
i think this should work
``{
	"query": {
		"filter": [
			{
				"term": {
					"_projectId": ""
				}
			},
			{
				"term": {
					"id": ""
				}
			},
			{
				"term": {
					"_modified": ""
				}
			}
		]
	}
	"from": 0,
	"size": 1
}``
or use checksum, but then you'll need to calculate checksum before check...

2018-04-16 19:39 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    pgh.getCommitAndTimestamp("timestamp", Long.toString(created.getTime()));
does comparing timestamp to string work? getTime returns in ms and postgres stores with higher precision?

2018-04-16 19:41 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
>                                  if (pgh.getArtifactFromSysmlId(artifactId, true) == null) {
really only need to do this for the latest version of the file

2018-04-16 20:33 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    elasticId = check.get(Sjm.ELASTICID).getAsString();
Hmm, are you sure? Because if we don't overwrite elasticId and commitId, it'll use the generated ones. I guess it would be ok if we just inserted the artifact at the end, instead of trying to update the record with every version.

2018-04-16 23:04 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                        eh.bulkUpdateElements(mdArtifacts, artifactToElementScript, projectId, "element");
mdArtifacts has the sysmlid of the elements but not elastic ids, should query elastic for all element objects whose id is in mdArtifacts

2018-04-16 23:04 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        "{\"script\": {\"inline\": \"ctx._source._artifacts = [ctx._source.id + \"_svg\", ctx._source.id + \"_png\"]}\"}}";
artifactIds

2018-04-17 03:26 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                                    elasticId = check.get(Sjm.ELASTICID).getAsString();
oh right, guess leave it then in case the last version was already in

2018-04-19 03:02 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> -                                    JsonArray inRefIds = new JsonArray();
actually should just add empty array

2018-04-19 03:03 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        "{\"query\": { \"match_all\":{} }, \"script\": {\"inline\": \"if(ctx._source.containsKey(\"_isSite\")){ctx._source._isGroup = ctx._source.remove(\"_isSite\")}\"}}";
the query can query on exists _isSite

2018-04-19 03:06 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                        List<String> nodeElasticIds = pgh.getElasticIdsFromSysmlIdsNodes(mdArtifactList, false);
this should actually not get from the db since it only have the latest elements, but we want all elements including historical with that id to have the artifactIds list, can prob just do a elastic update by query

2018-04-19 03:08 UTC, dlamoris reviewed
stuff

2018-04-20 02:56 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        "{\"query\": { \"term\":{\"id\":[\"%s\"]} }, \"script\": {\"inline\": \"ctx._source._artifactIds = [ctx._source.id + \\\"_svg\\\", ctx._source.id + \\\"_png\\\"]\"}}";
terms.....

2018-04-20 03:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        "{\"query\": { \"term\":{\"id\":[\"%s\"]} }, \"script\": {\"inline\": \"ctx._source._artifactIds = [ctx._source.id + \\\"_svg\\\", ctx._source.id + \\\"_png\\\"]\"}}";
Actually, terms is a filter. But there's also a term query. I think either is fine, unless you see a reason it's not? https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-term-query.html

2018-04-20 03:56 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        "{\"query\": { \"term\":{\"id\":[\"%s\"]} }, \"script\": {\"inline\": \"ctx._source._artifactIds = [ctx._source.id + \\\"_svg\\\", ctx._source.id + \\\"_png\\\"]\"}}";
Oops, array

2018-04-20 05:04 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +        "{\"query\": { \"term\":{\"id\":[\"%s\"]} }, \"script\": {\"inline\": \"ctx._source._artifactIds = [ctx._source.id + \\\"_svg\\\", ctx._source.id + \\\"_png\\\"]\"}}";
terms can be a query too, the elastic docs don't always show every possible way to use it, but filter would actually make more sense here

2018-04-20 05:08 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/actions/migrations/Migrate_3_3_0.java
> +                    List<Map<String, Object>> refCommits = pgh.getRefsCommits(ref.first);
getRefsCommits gets commits from parent refs too, those would get updated with the wrong _refId

2018-04-21 04:42 UTC, merged