Manage Database Connections Across Entire System
Open-MBEE/mms-alfresco pull request #276
Opened 2018-05-11 12:49 UTC by BA-MBSE

MMS is maintaining 2 database connections per project.  On a system with hundreds of projects, this becomes a problem.  This is an attempt to enforce some kind of limitation on the number of idle connections without sacrificing too much performance.

2018-05-14 17:16 UTC, HuiJun commented
There will most likely be a couple conflicts once the release branch is merged into develop. This PR will have to wait for the release.

2018-05-14 20:41 UTC, HuiJun requested changes

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        goActive();
This seems strange to me. Why not let BasicDataSource handle the reuse of connections?

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        if(basicDataSourceFactory == null)
Curly braces.

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        for(Cache<String, PostgresPool> cache : activeDataSources.values())
Again, curly braces

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    static final String PG_SEC = "pg.secured";
This will have to be added to the mms.properties.example file.

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +                    if (v.getCause() != RemovalCause.REPLACED)
Nitpicking, but I like curly braces.

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    static final int MIN_IDLE_CONN = 0;
The default minimum idle connections should already be 0.

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        this.bds.setMinIdle(MIN_IDLE_CONN);
Does nothing.

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    private static Cache<String, PostgresPool> getActiveDatasetCache(String host){
Can this be explained? Why do this instead of using the default evictor thread?

2018-05-14 20:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        this.bds.setTimeBetweenEvictionRunsMillis(1000*60);
This and setMinEvictableIdleTimeMillis seem like the only things that are needed...

2018-05-14 20:45 UTC, BA-MBSE commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        this.bds.setMinIdle(MIN_IDLE_CONN);
True, but adds clarity

2018-05-14 20:47 UTC, BA-MBSE commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    private static Cache<String, PostgresPool> getActiveDatasetCache(String host){
It is using the evictor thread within each BasicDataSource.  The BasicDataSource manages connections to a single database only.  The introduction of the cache adds a level of coordination between the individual BasicDataSource instances for each database host.

2018-05-14 20:49 UTC, BA-MBSE commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        goActive();
BasicDataSource handles reuse for a single connect string.  But there is no coordination if you have multiple connect strings to a single PS instance.  It's easy to overload PS when you have hundreds of projects.

2018-05-14 20:53 UTC, BA-MBSE commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        this.bds.setTimeBetweenEvictionRunsMillis(1000*60);
It could be simplified to that + MAX_IDLE_CONN = 0, yes.  But in our situation we will run the risk of exceeding the connection count with an unclear warning, and also will take a performance hit with disallowing idle connections.  This solution adjusts the max idle count based on usage to minimize performance impacts.

2018-05-14 21:07 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        goActive();
Ah, single pg instances...

2018-05-14 21:10 UTC, HuiJun commented
Ok, let's just fix the formatting and it looks good to me.

2018-05-14 21:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        if(EmsConfig.get(PG_SEC).toLowerCase().equals("true")){
Formatting

2018-05-14 21:41 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        if(this.bds.getNumActive() > 0){
Formatting

2018-05-14 21:42 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    private static Cache<String, PostgresPool> getActiveDatasetCache(String host){
Formatting

2018-05-14 21:42 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    static void purgeDatabasePools(){
Formatting

2018-05-14 21:42 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +    static void idleDatabasePools(){
Formatting

2018-05-14 21:48 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        this.bds.setTimeBetweenEvictionRunsMillis(1000*60);
Formatting

2018-05-14 21:48 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/PostgresPool.java
> +        this.bds.setMinEvictableIdleTimeMillis(1000*60*5);
Formatting

2018-05-15 12:40 UTC, BA-MBSE commented
Requested changes completed.  Thanks!

2018-06-28 18:21 UTC, HuiJun approved these changes

2018-06-28 21:22 UTC, merged