Feature/mms 966
Open-MBEE/mms-alfresco pull request #302
Opened 2018-08-10 16:15 UTC by lauraerinmann

In progress

2018-08-13 06:32 UTC, dlamoris requested changes

2018-08-13 06:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            if (elements.get(key).getAsJsonObject().has(Sjm.ASSOCIATIONENDID)) {
it should be associationId, not associationEndId,
also all elements.get(key) are already JsonObject, no need to getAsJsonObject()

2018-08-13 06:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    ownedAttributeIdsToAdd.set(index, new JsonParser().parse(id).getAsJsonObject());
this doesn't insert it, just replaces what's there, also I don't think getAsJsonObject works on a string, you may just have to change it to a java list before the loop and change it back after

2018-08-13 06:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +        boolean withChildViews = false;
withChildViews should be true

2018-08-13 06:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +                newElementsObject.addProperty(Sjm.CREATOR, user);
need to add the elements array, also add the if block for withChildViews similar to model post
actually everything from results = emsNodeUtil.processPostJson on should be the same as model post

2018-08-13 06:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +            JsonArray moved = emsNodeUtil.processMove(postJson.get(Sjm.MOVES).getAsJsonArray());
this can throw exceptions in lots of cases where the various ids given by user are not found, should return error code for those

2018-08-13 06:32 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        Map<String, JsonObject> elements = new HashMap<>();
there's lots of places where elements.get(key) will throw npe if an element id doesn't exist or is deleted, etc, catch in MovePost and return 400

2018-08-14 00:25 UTC, HuiJun requested changes

2018-08-14 00:25 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +        String contentType = req.getContentType() == null ? "" : req.getContentType().toLowerCase();
You can take this out.

2018-08-14 00:25 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +        boolean extended = false;
Do we need this?

2018-08-14 00:25 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        Map<String, Map> toAdd = new HashMap<>();
Is there a reason that you're instantiating these as raw types?

2018-08-14 00:25 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        Map<String, Map> toAdd = new HashMap<>();
toRemove and toAdd

2018-08-14 17:02 UTC, lauraerinmann commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        Map<String, JsonObject> elements = new HashMap<>();
The method is already called inside a try/catch block in MovePost that calls a 400 if it fails.  Did you need me to alter it someplace else?

2018-08-14 18:51 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        Map<String, JsonObject> elements = new HashMap<>();
it looks like the 400 is only for IllegalStateException, any other exception it just logs it?

2018-08-15 03:46 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelPost.java
> +import org.json.JSONObject;
wat

2018-08-15 03:48 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +
These imports need to be cleaned up.

2018-08-15 05:16 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                String associationId = elements.get(key).get(Sjm.ASSOCIATIONENDID).getAsString();
associationId, not associationEndId

2018-08-15 05:20 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +        String contentType = req.getContentType() == null ? "" : req.getContentType().toLowerCase();
not needed either

2018-08-15 05:23 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +        JsonObject results;
unused vars

2018-08-15 05:26 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    ownedAttributeIdsToAdd.add(index, new JsonParser().parse(id).getAsJsonObject());
should just add id, not json object

2018-08-15 05:34 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +            moved = emsNodeUtil.processMove(postJson.get(Sjm.MOVES).getAsJsonArray());
add the source and comment fields from postJson to the wrapper object if they exist

2018-08-16 21:15 UTC, HuiJun requested changes

2018-08-16 21:15 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        HashMap<String, List> toRemove = new HashMap<>();
List is the raw type I was referring to.

2018-08-16 21:15 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +        HashMap<String, Map> toAdd = new HashMap<>();
The raw Map in Map<String, Map> is the raw type I was referring to...

2018-08-17 03:41 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +            List ownedAttributeIdsToAdd =
should be declared as List<String>

2018-08-17 03:41 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/util/EmsNodeUtil.java
> +                    ownedAttributeIdsToAdd.add(index, new JsonParser().parse(id));
should not parse id but use it directly

2018-08-17 03:48 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/MovePost.java
> +        } catch (IllegalStateException e) {
IllegalStateException will not bubble up here since it's already caught in createDeltaForMove, and there's no handler here for other exceptions that can occur

2018-08-22 15:42 UTC, HuiJun approved these changes

2018-08-22 17:16 UTC, merged