Feature/mms 972
Open-MBEE/mms-alfresco pull request #310
Opened 2018-08-23 16:56 UTC by HuiJun

2018-08-23 18:21 UTC, dlamoris requested changes

2018-08-23 18:21 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
>                  JsonUtil.addStringSet(result, Sjm.FAILED, elementsToFind);
can remove this line

2018-08-23 18:21 UTC, dlamoris commented on mms-ent/repo-amp/src/main/resources/mapping_template.json
> +                "name": {
name shouldn't be keyword...i think just leave it as default,
also add parentCommitId and other stuff..

2018-08-23 18:21 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/WorkspacesPost.java
> +            wsJson.addProperty(Sjm.ELASTICID, existingWsJson.get(Sjm.ELASTICID).getAsString());
should also remove any parent* keys, or throw 400 is they're found

2018-08-23 18:21 UTC, dlamoris commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +    public ElasticResult updateElement(JsonObject j, String index, String eType) throws IOException {
there's a function called updateProfile currently being used by user preference post that can be combined

2018-08-23 18:27 UTC, dlamoris commented on mms-ent/repo-amp/src/main/resources/mapping_template.json
> +                "name": {
actually name can't be keyword because all types in an index share the same mapping for the same field

2018-08-23 21:47 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/db/ElasticHelper.java
> +    public ElasticResult updateElement(JsonObject j, String index, String eType) throws IOException {
Yeah, I'm going to combine all of these ridiculous methods

2018-08-23 22:19 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/ModelGet.java
>                  JsonUtil.addStringSet(result, Sjm.FAILED, elementsToFind);
Oh, I thought I removed all those lines

2018-08-24 00:35 UTC, HuiJun commented on mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/WorkspacesPost.java
> +            wsJson.addProperty(Sjm.ELASTICID, existingWsJson.get(Sjm.ELASTICID).getAsString());
This was implemented in WorkspacesPost.java starting on line 688

2018-08-24 17:25 UTC, dlamoris approved these changes

2018-08-25 06:13 UTC, merged